### PR TITLE
Fix/web assembly recorder

### PR DESCRIPTION
**Pull request by jonklein**
Several fixes & improvements for issues I found in using WebAssemblyRecorder:

- fix audio feedback: set video element to muted 

- fix truncated video content: don't terminate the worker immediately, wait for the final message indicating that encoding is complete

- fix video timescale not matching framerate: use setInterval instead of repeated setTimeouts to make sure frames are timed correctly instead of slipping

- add a `onVideoProcessStarted` callback, which is useful for better synchronization of audio/video from different recorders

- add `realtime` flag, defaulted to true (current behavior), to allow for non-realtime (higher quality) encoding.  this is *very* slow, but may be useful.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
can you add a new release with this @muaz-khan?

**Comment by thijstriemstra** [comment]
@jonklein did you test this with Firefox and polyfill, e.g. the online demo? https://www.webrtc-experiment.com/RecordRTC/simple-demos/WebAssemblyRecorder.html

It breaks the demo (and my project relying on recordrtc) so I have to revert back to recordrtc 5.5.9 for now unfortunately.

cc @muaz-khan

**Comment by thijstriemstra** [comment]
screenshot: 
Screenshot from 2020-05-17 18-16-51

**Comment by muaz-khan** [comment]
@thijstriemstra Please check https://github.com/muaz-khan/RecordRTC/commit/1fd3e0304c0b4b72ea37b644cbe40efa9f0e654e . And test demo again on Firefox.
* https://www.webrtc-experiment.com/RecordRTC/simple-demos/WebAssemblyRecorder.html

**Comment by thijstriemstra** [comment]
thanks @muaz-khan looks good now.

**Pull request merged**
