### PR TITLE
add timeslice and onTimeStamp options in MRecordRTC

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
the travis builder seems broken: https://travis-ci.org/muaz-khan/RecordRTC/builds/243289806#L305

**Comment by muaz-khan** [comment]
https://travis-ci.org/muaz-khan/RecordRTC has (i.e. defines+requires) following two environment variables (to use browserstack services).

* https://github.com/muaz-khan/RecordRTC/blob/master/test/browserstack.config.js#L19-L20

Travis build works if manually (myself) **merge pull-requests** or add commits. Because now travis can use my environment variables.

**Comment by thijstriemstra** [comment]
Thanks @muaz-khan. Can you also release a new version, last one is from march.. Cheers.

**Comment by muaz-khan** [comment]
* http://recordrtc.org/RecordRTC.html#getInternalRecorder

```javascript
// below 3 are RecordRTC instances:
// 1) mRecordRTC.audioRecorder
// 2) mRecordRTC.videoRecorder
// 2) mRecordRTC.gifRecorder

// RecordRTC exports "getInternalRecorder" method
var internal = mRecordRTC.videoRecorder.getInternalRecorder();

// only for MediaStreamRecorder
// i.e.     (internal instanceof MediaStreamRecorder) === true
var buffers = internal.getArrayBuffers();
var blob = new Blob(buffers, {
    type: 'video/webm'
});
```

**Comment by thijstriemstra** [comment]
Thanks, turns out I was using an old CDN version (downloaded yesterday) but it's latest version works now.

**Comment by thijstriemstra** [comment]
@muaz-khan it seems setting `timeSlice` to a different value doesn't have any impact? is this a bug?

**Pull request merged**
